interface store {
  CLIENT_ID: string,
  SECRET_KEY: string,
  CLIENT_ACCESS_TOKEN: string
}

export default (): store => ({
  CLIENT_ID: 'orECZ9pUVtOFx6KJ-GWJzsdTt3m5Te39cuOb1d8fZP_GIxM3LNMx1UlFWMFS2VXd',
  SECRET_KEY: '2CeU4XsjiIeuF_Ujuk4AE9LbGiKUIg9RJ8vCSMEVOYT9CLK1MwYEK2K-dR7H7c8RLE6rZL4MXYDw5un9jQoRSw',
  CLIENT_ACCESS_TOKEN: 'tB5ToniZwQrAkQWQhp8hNPZLzLRUAURc0bcQu5T6c252kHj2K1ejTSjS4OBhKqeH'
})
